"""feat: Gemeinderatsperiode - 5 Jahres Perioden mit Personenverwaltung

Revision ID: 1299bed2f94d
Revises: 
Create Date: 2026-06-10 22:59:17.690640
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '1299bed2f94d'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gemeinderatsperiode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('start_jahr', sa.Integer(), nullable=False),
    sa.Column('end_jahr', sa.Integer(), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vorname', sa.String(length=100), nullable=False),
    sa.Column('nachname', sa.String(length=100), nullable=False),
    sa.Column('titel', sa.String(length=50), nullable=False),
    sa.Column('partei', sa.String(length=50), nullable=True),
    sa.Column('gremium', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('invite_token', sa.String(length=255), nullable=True),
    sa.Column('invite_expires', sa.DateTime(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sitzungsregel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('block_minuten', sa.Integer(), nullable=False),
    sa.Column('sitzung_minuten', sa.Integer(), nullable=False),
    sa.Column('pause_minuten', sa.Integer(), nullable=False),
    sa.Column('council_minuten', sa.Integer(), nullable=False),
    sa.Column('quorum_standard', sa.Integer(), nullable=False),
    sa.Column('quorum_poly', sa.Integer(), nullable=False),
    sa.Column('quorum_kontroll', sa.Integer(), nullable=False),
    sa.Column('planungswochen', sa.Integer(), nullable=False),
    sa.Column('freitag_modus', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('abwesenheit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('von', sa.Date(), nullable=False),
    sa.Column('bis', sa.Date(), nullable=False),
    sa.Column('art', sa.Enum('URLAUB', 'KRANKHEIT', 'DIENSTREISE', 'ENTSCHULDIGT', 'SONSTIGES', name='abwesenheitsart'), nullable=False),
    sa.Column('bemerkung', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ausschuss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('typ', sa.Enum('STANDARD', 'POLY', 'KONTROLL', name='ausschusstyp'), nullable=False),
    sa.Column('turnus', sa.String(length=50), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('quorum_override', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['periode_id'], ['gemeinderatsperiode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jahresplan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=True),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=150), nullable=False),
    sa.Column('variante', sa.Integer(), nullable=False),
    sa.Column('grund_variante', sa.String(length=255), nullable=False),
    sa.Column('aktiv', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['periode_id'], ['gemeinderatsperiode.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('periode_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('start_datum', sa.Date(), nullable=False),
    sa.Column('end_datum', sa.Date(), nullable=True),
    sa.Column('grund_austritt', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['periode_id'], ['gemeinderatsperiode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_id', 'person_id', name='uq_periode_person')
    )
    op.create_table('verfuegbarkeit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('wochentag', sa.Enum('MO', 'DI', 'MI', 'DO', 'FR', name='wochentag'), nullable=False),
    sa.Column('stunde', sa.Integer(), nullable=False),
    sa.Column('verfuegbar', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id', 'wochentag', 'stunde', name='uq_verfuegbarkeit')
    )
    op.create_table('mitgliedschaft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('periode_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('ausschuss_id', sa.Integer(), nullable=False),
    sa.Column('rolle', sa.Enum('OBMANN', 'OBMANN_STELLVERTRETER', 'MITGLIED', name='rolle'), nullable=False),
    sa.ForeignKeyConstraint(['ausschuss_id'], ['ausschuss.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['periode_id'], ['gemeinderatsperiode.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periode_id', 'person_id', 'ausschuss_id', name='uq_mitgliedschaft_periode')
    )
    op.create_table('sitzungsvorschlag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ausschuss_id', sa.Integer(), nullable=False),
    sa.Column('woche', sa.Integer(), nullable=False),
    sa.Column('wochentag', sa.Enum('MO', 'DI', 'MI', 'DO', 'FR', name='wochentag'), nullable=False),
    sa.Column('start_minute', sa.Integer(), nullable=False),
    sa.Column('end_minute', sa.Integer(), nullable=False),
    sa.Column('anwesend_count', sa.Integer(), nullable=False),
    sa.Column('mitglieder_count', sa.Integer(), nullable=False),
    sa.Column('quote', sa.Integer(), nullable=False),
    sa.Column('obmann_da', sa.Boolean(), nullable=False),
    sa.Column('stv_da', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('TOP', 'BESCHLUSSFAEHIG', 'ALTERNATIV', 'OBMANN_DA', 'NICHT_BESCHLUSSFAEHIG', name='terminstatus'), nullable=False),
    sa.Column('fehlende', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ausschuss_id'], ['ausschuss.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sitzungsvorschlag')
    op.drop_table('mitgliedschaft')
    op.drop_table('verfuegbarkeit')
    op.drop_table('periode_person')
    op.drop_table('jahresplan')
    op.drop_table('ausschuss')
    op.drop_table('abwesenheit')
    op.drop_table('sitzungsregel')
    op.drop_table('person')
    op.drop_table('gemeinderatsperiode')
    # ### end Alembic commands ###
